SET search_path = restaurante, pg_catalog;
drop function "atualizaMesa"()  cascade;

insert into funcionario(cpf,nome,funcao,salario,sexo) values('00000000001','Augusto Ribas','garcom',880.00,'M');
insert into funcionario(cpf,nome,funcao,salario,sexo) values('00000000002','Bruno Nazario','garcom',880.00,'M');
insert into mesa(id,disponibilidade,capacidade) values(1,BIT'1',8);
insert into mesa(id,disponibilidade,capacidade) values(2,BIT'1',6);
insert into atendimento(datahora,funcionario_cpf) values('2016-07-05 12:00:00','00000000001');
insert into atendimento(datahora,funcionario_cpf) values('2016-07-05 12:00:00','00000000002');
insert into mesa_has_atendimento(mesa_id,atendimento_idatendimento) values (1,1);
insert into mesa_has_atendimento(mesa_id,atendimento_idatendimento) values (2,2);
insert into fabricante(nome,nacionalidade) values ('FEMSA','BRA');
insert into tipoBebida(nome) values('Refrigerante');
insert into bebida(nome,preco_venda,tipobebida_idtipobebida,fabricante_idfabricante) values ('Coca Cola',3.50,1,1);
insert into atendimento_has_bebida(bebida_idbebida,atendimento_idatendimento,preco_pago) values (1,1,7);
insert into atendimento_has_bebida(bebida_idbebida,atendimento_idatendimento,preco_pago) values (1,2,3.50);
insert into item(nome) values('hamburguer');
insert into item(nome) values('pao');
insert into tipoprato(nome) values ('sanduiche');
insert into prato(nome,preco_venda,tipoprato_idtipoprato) values('Hamburguer Simples',10.00,1);
insert into prato_has_item(prato_idprato,item_iditem) values(1,1);
insert into prato_has_item(prato_idprato,item_iditem) values(1,2);
insert into prato_has_atendimento(prato_idprato,atendimento_idatendimento,preco_pago) values (1,1,12);
insert into prato_has_atendimento(prato_idprato,atendimento_idatendimento,preco_pago) values (1,2,12);
