all: rodar

rodar: Ingresso.class Normal.class Vip.class TesteIngresso.class Inferior.class Superior.class
	java TesteIngresso

Ingresso.class:
	javac Ingresso.java

Normal.class:
	javac Normal.java

Vip.class:
	javac Vip.java

Inferior.class:
	javac Inferior.java

Superior.class:
	javac Superior.java

TesteIngresso.class:
	javac TesteIngresso.java

clean:
	rm *.class